# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170930_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
