# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170930_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
