# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_part_part_storage_locaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
            preserve_default=False,
        ),
    ]
